variables:
  GIT_CLEAN_FLAGS: none

stages:
  - test
  - deploy

unitTests:
  stage: test
  script:
    - ./gradlew clean
    - ./gradlew testDebugUnitTest

appTests:
  stage: test
  script:
    - ./gradlew clean
    - ./gradlew cDAT testDebug

deployRelease:
  stage: deploy
  only:
    - tags
  script:
    - ./gradlew publish

