variables:
  GIT_CLEAN_FLAGS: none

stages:
  - test
  - deploy

appTests:
  stage: test
#  script:
#    - ./gradlew cDAT testDebug

deployRelease:
  stage: deploy
  only:
    - tags
  script:
    - ./gradlew publish

