variables:
  GIT_CLEAN_FLAGS: none

stages:
  - test
  - deploy

appTests:
  stage: test
  script:
    - ./gradlew app:test app:cAT

deployRelease:
  stage: deploy
  only:
    - tags
  script:
    - ./gradlew publish

